export const EVENT_TYPES = [
  'ProjectCreated',
  'StoryCreated',
  'StoryRevisionCreated',
  'TaskCreated',
  'TaskStateChanged',
  'AnalysisStarted',
  'FileInspected',
  'ResearchCompleted',
  'ReviewGenerated',
  'HumanNoteAdded',
  'ReviewRegenerated',
  'ReviewApproved',
  'HighRiskConfirmed',
  'SupplementalReviewCreated',
  'ImplementationStarted',
  'ToolCalled',
  'FileModified',
  'TestStarted',
  'TestPassed',
  'TestFailed',
  'BuildStarted',
  'BuildFailed',
  'FixStarted',
  'QAStarted',
  'QARejected',
  'QAApproved',
  'FinalReviewGenerated',
  'PRApproved',
  'PRCreated',
  'TaskCompleted',
  'TaskBlocked',
  'TaskPaused',
  'TaskResumed',
  'TaskStopped',
  'TaskFailed',
  'CheckpointCreated',
  'SandboxCreated',
  'SandboxDestroyed',
  'ConflictDetected',
  'BaseMoved',
  'PrincipleLearned',
  'InvariantExtracted',
  'KnowledgeSnapshotCreated',
  'RuntimeManifestGenerated',
  'InstallationCandidateReady',
  'InstallationApplyStarted',
  'InstallationApplyFinished',
] as const;

export type EventType = (typeof EVENT_TYPES)[number];

export const ACTOR_TYPES = ['human', 'agent', 'orchestrator', 'worker', 'system'] as const;
export type ActorType = (typeof ACTOR_TYPES)[number];
