import { newId, NotFoundError } from '@ai-engine/shared';
import type { ExecutionPhase, TaskCheckpoint, TaskRun, ToolCall } from '@ai-engine/domain';
import type { Queryable } from '../client';
import { camelize, camelizeAll } from '../mapping';

const RUN_COLUMNS = `id, task_id, project_id, kind, subject_id, phase, agent_type, agent_version_id, status,
  started_at, finished_at, input_tokens, output_tokens, cache_read_tokens, cache_creation_tokens, cost_usd,
  model_usage, subagent_stats, session_id, resumed, effort, model, error_message`;

/** What a finished run spent. Anything omitted leaves the stored value alone. */
export interface RunCompletion {
  inputTokens?: number;
  outputTokens?: number;
  cacheReadTokens?: number;
  cacheCreationTokens?: number;
  costUsd?: number | null;
  modelUsage?: Record<string, unknown> | null;
  subagentStats?: Record<string, unknown> | null;
  /** The id the engine actually reported, which may differ from the one sent. */
  sessionId?: string | null;
  resumed?: boolean | null;
  effort?: string | null;
  model?: string | null;
}

/**
 * One agent's usage inside a time window, in tokens.
 *
 * There is no money here on purpose. The engine reports a cost and the column
 * keeps it, because discarding a measurement cannot be undone, but the account
 * this runs on is a subscription with a weekly token limit, so a dollar figure
 * answers a question nobody is asking and invites reading it as the bill.
 */
export interface AgentUsage {
  agentType: string;
  runs: number;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheCreationTokens: number;
  /** Runs in the window that recorded nothing, so the sum is partial. */
  unrecordedRuns: number;
  /** Runs in the window that failed. What they spent is counted, not hidden. */
  failedRuns: number;
}

export class TaskRunRepository {
  constructor(private readonly db: Queryable) {}

  async start(input: {
    /** Null for work that is not a task: an idea intake or a chat turn. */
    taskId?: string | null;
    projectId: string;
    kind?: TaskRun['kind'];
    /** The idea session or chat session, when this is not a task run. */
    subjectId?: string | null;
    phase: ExecutionPhase;
    agentType: string;
    agentVersionId?: string | null;
    /**
     * The session this run will continue, when the caller already knows it.
     * Recorded here rather than on completion so that a run which dies before it
     * produces anything still says which conversation it was in.
     */
    sessionId?: string | null;
    resumed?: boolean | null;
  }): Promise<TaskRun> {
    const row = await this.db.queryOne(
      `INSERT INTO task_runs (id, task_id, project_id, kind, subject_id, phase, agent_type, agent_version_id,
         session_id, resumed)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING ${RUN_COLUMNS}`,
      [
        newId(),
        input.taskId ?? null,
        input.projectId,
        input.kind ?? 'TASK',
        input.subjectId ?? null,
        input.phase,
        input.agentType,
        input.agentVersionId ?? null,
        input.sessionId ?? null,
        input.resumed ?? null,
      ],
    );
    return camelize<TaskRun>(row!);
  }

  /**
   * Records the session the engine opened, at the moment it opens it.
   *
   * A cold run's session id is generated by the engine, so the caller cannot
   * know it at start; this is how it reaches the row before the process can
   * fail. Engines without sessions never call it and leave both columns NULL.
   */
  async recordSession(id: string, session: { sessionId: string; resumed: boolean }): Promise<void> {
    await this.db.query('UPDATE task_runs SET session_id = $2, resumed = $3 WHERE id = $1', [
      id,
      session.sessionId,
      session.resumed,
    ]);
  }

  async complete(id: string, spend?: RunCompletion): Promise<TaskRun> {
    const row = await this.db.queryOne(
      `UPDATE task_runs SET status = 'COMPLETED', finished_at = now(),
         input_tokens = COALESCE($2, input_tokens), output_tokens = COALESCE($3, output_tokens),
         cache_read_tokens = COALESCE($4, cache_read_tokens),
         cache_creation_tokens = COALESCE($5, cache_creation_tokens),
         cost_usd = COALESCE($6, cost_usd),
         model_usage = COALESCE($7::jsonb, model_usage),
         subagent_stats = COALESCE($8::jsonb, subagent_stats),
         session_id = COALESCE($9, session_id),
         resumed = COALESCE($10, resumed),
         effort = COALESCE($11, effort),
         model = COALESCE($12, model)
       WHERE id = $1 RETURNING ${RUN_COLUMNS}`,
      [
        id,
        spend?.inputTokens ?? null,
        spend?.outputTokens ?? null,
        spend?.cacheReadTokens ?? null,
        spend?.cacheCreationTokens ?? null,
        spend?.costUsd ?? null,
        spend?.modelUsage ? JSON.stringify(spend.modelUsage) : null,
        spend?.subagentStats ? JSON.stringify(spend.subagentStats) : null,
        spend?.sessionId ?? null,
        spend?.resumed ?? null,
        spend?.effort ?? null,
        spend?.model ?? null,
      ],
    );
    if (!row) throw new NotFoundError('TaskRun', id);
    return camelize<TaskRun>(row);
  }

  /**
   * A failed run still spent what it spent. The engine reports its usage on the
   * error path too, so it is recorded here rather than thrown away; a figure
   * that counts only the runs which succeeded hides where much of the money went.
   */
  async fail(id: string, errorMessage: string, spend?: RunCompletion): Promise<TaskRun> {
    const row = await this.db.queryOne(
      `UPDATE task_runs SET status = 'FAILED', finished_at = now(), error_message = $2,
         input_tokens = COALESCE($3, input_tokens), output_tokens = COALESCE($4, output_tokens),
         cache_read_tokens = COALESCE($5, cache_read_tokens),
         cache_creation_tokens = COALESCE($6, cache_creation_tokens),
         cost_usd = COALESCE($7, cost_usd),
         model_usage = COALESCE($8::jsonb, model_usage),
         subagent_stats = COALESCE($9::jsonb, subagent_stats),
         session_id = COALESCE($10, session_id),
         resumed = COALESCE($11, resumed),
         effort = COALESCE($12, effort),
         model = COALESCE($13, model)
       WHERE id = $1 RETURNING ${RUN_COLUMNS}`,
      [
        id,
        errorMessage.slice(0, 4000),
        spend?.inputTokens ?? null,
        spend?.outputTokens ?? null,
        spend?.cacheReadTokens ?? null,
        spend?.cacheCreationTokens ?? null,
        spend?.costUsd ?? null,
        spend?.modelUsage ? JSON.stringify(spend.modelUsage) : null,
        spend?.subagentStats ? JSON.stringify(spend.subagentStats) : null,
        spend?.sessionId ?? null,
        spend?.resumed ?? null,
        spend?.effort ?? null,
        spend?.model ?? null,
      ],
    );
    if (!row) throw new NotFoundError('TaskRun', id);
    return camelize<TaskRun>(row);
  }

  async listByTask(taskId: string): Promise<TaskRun[]> {
    return camelizeAll<TaskRun>(
      await this.db.query(`SELECT ${RUN_COLUMNS} FROM task_runs WHERE task_id = $1 ORDER BY started_at ASC`, [taskId]),
    );
  }

  async latestForPhase(taskId: string, phase: ExecutionPhase): Promise<TaskRun | null> {
    const row = await this.db.queryOne(
      `SELECT ${RUN_COLUMNS} FROM task_runs WHERE task_id = $1 AND phase = $2 ORDER BY started_at DESC LIMIT 1`,
      [taskId, phase],
    );
    return row ? camelize<TaskRun>(row) : null;
  }

  /**
   * What each agent used on runs that finished inside the window, in tokens.
   *
   * The scope is the run's own project rather than a join through tasks, because
   * an idea intake and a chat turn have no task and would otherwise be missing
   * from the only figure that says how much of the week is gone. Passing null
   * counts every project, which is what the account limit actually applies to.
   *
   * Failed runs are counted. A run that burned thirty thousand output tokens and
   * then failed is usage, and leaving it out was the single largest way this
   * figure understated what the agents cost.
   *
   * Every aggregate is cast to text and converted here, as the metrics summary
   * does: SUM over an INTEGER column is a bigint, which node-postgres returns as
   * a string that would concatenate rather than add.
   */
  async usageSince(projectId: string | null, since: Date): Promise<AgentUsage[]> {
    const rows = await this.db.query<{
      agent_type: string;
      runs: string;
      input_tokens: string;
      output_tokens: string;
      cache_read_tokens: string;
      cache_creation_tokens: string;
      unrecorded_runs: string;
      failed_runs: string;
    }>(
      `SELECT r.agent_type,
              COUNT(*)::text AS runs,
              COALESCE(SUM(r.input_tokens), 0)::text AS input_tokens,
              COALESCE(SUM(r.output_tokens), 0)::text AS output_tokens,
              COALESCE(SUM(r.cache_read_tokens), 0)::text AS cache_read_tokens,
              COALESCE(SUM(r.cache_creation_tokens), 0)::text AS cache_creation_tokens,
              (COUNT(*) FILTER (WHERE r.input_tokens IS NULL AND r.output_tokens IS NULL))::text AS unrecorded_runs,
              (COUNT(*) FILTER (WHERE r.status = 'FAILED'))::text AS failed_runs
         FROM task_runs r
        WHERE ($1::uuid IS NULL OR r.project_id = $1::uuid)
          AND r.status IN ('COMPLETED', 'FAILED')
          AND r.finished_at >= $2
        GROUP BY r.agent_type
        ORDER BY r.agent_type`,
      [projectId, since.toISOString()],
    );
    return rows.map((row) => ({
      agentType: row.agent_type,
      runs: Number(row.runs),
      inputTokens: Number(row.input_tokens),
      outputTokens: Number(row.output_tokens),
      cacheReadTokens: Number(row.cache_read_tokens),
      cacheCreationTokens: Number(row.cache_creation_tokens),
      unrecordedRuns: Number(row.unrecorded_runs),
      failedRuns: Number(row.failed_runs),
    }));
  }

  /** Every run of one idea session or chat session, newest last. */
  async listBySubject(subjectId: string): Promise<TaskRun[]> {
    return camelizeAll<TaskRun>(
      await this.db.query(`SELECT ${RUN_COLUMNS} FROM task_runs WHERE subject_id = $1 ORDER BY started_at ASC`, [
        subjectId,
      ]),
    );
  }

  /** Marks runs that were interrupted by a crash so the UI never shows them as live. */
  async failStaleRuns(olderThanMinutes: number): Promise<number> {
    const rows = await this.db.query(
      `UPDATE task_runs SET status = 'FAILED', finished_at = now(), error_message = 'Run was interrupted'
       WHERE status = 'RUNNING' AND started_at < now() - ($1 || ' minutes')::interval RETURNING id`,
      [String(olderThanMinutes)],
    );
    return rows.length;
  }
}

const TOOL_CALL_COLUMNS = `id, task_id, run_id, sequence, tool_name, input, output_summary,
  output_artifact_id, status, duration_ms, created_at`;

export class ToolCallRepository {
  constructor(private readonly db: Queryable) {}

  async record(input: {
    taskId: string;
    runId: string;
    sequence: number;
    toolName: string;
    input: Record<string, unknown>;
    outputSummary: string;
    outputArtifactId?: string | null;
    status: 'OK' | 'ERROR' | 'DENIED';
    durationMs: number;
  }): Promise<ToolCall> {
    const row = await this.db.queryOne(
      `INSERT INTO tool_calls (id, task_id, run_id, sequence, tool_name, input, output_summary, output_artifact_id, status, duration_ms)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING ${TOOL_CALL_COLUMNS}`,
      [
        newId(),
        input.taskId,
        input.runId,
        input.sequence,
        input.toolName,
        JSON.stringify(input.input),
        input.outputSummary.slice(0, 8000),
        input.outputArtifactId ?? null,
        input.status,
        input.durationMs,
      ],
    );
    return camelize<ToolCall>(row!);
  }

  async listByRun(runId: string): Promise<ToolCall[]> {
    return camelizeAll<ToolCall>(
      await this.db.query(`SELECT ${TOOL_CALL_COLUMNS} FROM tool_calls WHERE run_id = $1 ORDER BY sequence ASC`, [runId]),
    );
  }

  async listRecentByTask(taskId: string, limit = 50): Promise<ToolCall[]> {
    return camelizeAll<ToolCall>(
      await this.db.query(
        `SELECT ${TOOL_CALL_COLUMNS} FROM tool_calls WHERE task_id = $1 ORDER BY created_at DESC LIMIT $2`,
        [taskId, limit],
      ),
    );
  }
}

const CHECKPOINT_COLUMNS = `id, task_id, run_id, state, git_head, diff_artifact_id, workspace_metadata,
  migration_state, running_services, agent_versions, knowledge_snapshot_id, plan_position, created_at`;

export class CheckpointRepository {
  constructor(private readonly db: Queryable) {}

  async create(input: {
    taskId: string;
    runId?: string | null;
    state: string;
    gitHead?: string | null;
    diffArtifactId?: string | null;
    workspaceMetadata?: Record<string, unknown>;
    migrationState?: Record<string, unknown>;
    runningServices?: string[];
    agentVersions?: Record<string, string>;
    knowledgeSnapshotId?: string | null;
    planPosition?: number;
  }): Promise<TaskCheckpoint> {
    const row = await this.db.queryOne(
      `INSERT INTO task_checkpoints (id, task_id, run_id, state, git_head, diff_artifact_id, workspace_metadata,
         migration_state, running_services, agent_versions, knowledge_snapshot_id, plan_position)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING ${CHECKPOINT_COLUMNS}`,
      [
        newId(),
        input.taskId,
        input.runId ?? null,
        input.state,
        input.gitHead ?? null,
        input.diffArtifactId ?? null,
        JSON.stringify(input.workspaceMetadata ?? {}),
        JSON.stringify(input.migrationState ?? {}),
        JSON.stringify(input.runningServices ?? []),
        JSON.stringify(input.agentVersions ?? {}),
        input.knowledgeSnapshotId ?? null,
        input.planPosition ?? 0,
      ],
    );
    return camelize<TaskCheckpoint>(row!);
  }

  async latest(taskId: string): Promise<TaskCheckpoint | null> {
    const row = await this.db.queryOne(
      `SELECT ${CHECKPOINT_COLUMNS} FROM task_checkpoints WHERE task_id = $1 ORDER BY created_at DESC LIMIT 1`,
      [taskId],
    );
    return row ? camelize<TaskCheckpoint>(row) : null;
  }

  async listByTask(taskId: string): Promise<TaskCheckpoint[]> {
    return camelizeAll<TaskCheckpoint>(
      await this.db.query(`SELECT ${CHECKPOINT_COLUMNS} FROM task_checkpoints WHERE task_id = $1 ORDER BY created_at ASC`, [
        taskId,
      ]),
    );
  }
}
