import { randomUUID, createHash } from 'node:crypto';

/** All identifiers in the system are UUID v4 strings generated by the application. */
export function newId(): string {
  return randomUUID();
}

/** Stable content hash used for prompt/agent/version fingerprints. */
export function sha256(input: string): string {
  return createHash('sha256').update(input, 'utf8').digest('hex');
}

/** Short, human readable fingerprint of a longer hash. */
export function shortHash(input: string): string {
  return sha256(input).slice(0, 12);
}

/** Deterministic slug used for branch names and directories. */
export function slugify(value: string, maxLength = 48): string {
  const slug = value
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug.slice(0, maxLength).replace(/-+$/g, '') || 'story';
}
